# ASP.NET
- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'sample'
    specSource: 'taskConfiguration'
    failNoOp: true
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: JFrog.jfrog-artifactory-vsts-extension.artifactory-nuget.ArtifactoryNuGet@2
  displayName: 'Artifactory NuGet restore'
  inputs:
    command: 'restore'
    artifactoryService: 'sample'
    targetResolveRepo: 'nuget'
    solutionPath: '**/*.sln'
    noNuGetCache: true
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: '24aa8c93-dfa0-4938-a63c-3ff403087847'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(Parameters.ArtifactName)'
  condition: succeededOrFailed()
